version: '3'

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}
  local_media: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: paprika_sync_local_django
    depends_on:
      - postgres
      - mailhog
    volumes:
      - .:/app
      - local_media:/appmedia
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
    command: /start
    stdin_open: true
    tty: true

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: paprika_sync_production_postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
      - local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres

  traefik:
    build:
      context: .
      dockerfile: ./compose/local/traefik/Dockerfile
    image: paprika_sync_local_traefik
    depends_on:
      - django
    ports:
      - "0.0.0.0:8080:80"

  nginx:
    image: nginx:alpine
    volumes:
      - local_media:/usr/share/nginx/html/media:ro

  mailhog:
    image: mailhog/mailhog:v1.0.0
    ports:
      - "8025:8025"
