# Generated by Django 2.0.13 on 2019-02-18 22:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaprikaAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('username', models.CharField(help_text='Username to login to paprika', max_length=150)),
                ('password', models.CharField(help_text='Password to login to paprika', max_length=128)),
                ('alias', models.CharField(help_text='Name to associate with this account in news feed items (e.g. Alice, Bob)', max_length=150)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paprika_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('uid', models.CharField(max_length=200)),
                ('hash', models.CharField(max_length=200)),
                ('photo_hash', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('image_url', models.URLField()),
                ('paprika_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='core.PaprikaAccount')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
