# Generated by Django 2.0.13 on 2019-03-17 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paprikaaccount',
            name='import_status',
            field=models.CharField(blank=True, choices=[('deferred', 'deferred'), ('inprogress', 'inprogress'), ('success', 'success')], help_text='Status of importing all recipes', max_length=150),
        ),
    ]
