# Generated by Django 2.0.13 on 2019-03-17 01:41

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_paprikaaccount_import_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('new_account', 'new_account'), ('recipe_added', 'recipe_added'), ('recipe_edited', 'recipe_edited'), ('recipe_deleted', 'recipe_deleted')], max_length=100)),
                ('payload', django.contrib.postgres.fields.jsonb.JSONField(default=dict, help_text='Specifies details (e.g. what fields of a recipe were updated)')),
                ('paprika_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.PaprikaAccount')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
    ]
