# Generated by Django 2.0.13 on 2019-03-20 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_newsitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='date_ended',
            field=models.DateTimeField(db_index=True, help_text='Date when this version of the Recipe was superseded (unset if this is the active Recipe for this uid)', null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='uid',
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
