# Generated by Django 2.0.13 on 2019-06-22 14:26

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190320_1812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paprikaaccount',
            name='import_status',
        ),
        migrations.AddField(
            model_name='paprikaaccount',
            name='import_sync_status',
            field=django_fsm.FSMField(choices=[('new_account', 'new_account'), ('import_deferred', 'import_deferred'), ('import_inprogress', 'import_inprogress'), ('sync_requested', 'sync_requested'), ('sync_inprogress', 'sync_inprogress'), ('success', 'success'), ('import_failure', 'import_failure'), ('sync_failure', 'sync_failure')], default='new_account', help_text='Status of importing/syncing recipes', max_length=50, protected=True),
        ),
        migrations.AddField(
            model_name='paprikaaccount',
            name='last_synced',
            field=models.DateTimeField(help_text='When this account was last synced with the API', null=True),
        ),
        migrations.AddField(
            model_name='paprikaaccount',
            name='sync_failure_count',
            field=models.PositiveSmallIntegerField(default=0, help_text='Incremented for failures, to stop retrying if we are failing repeatedly'),
        ),
        migrations.AlterField(
            model_name='paprikaaccount',
            name='alias',
            field=models.CharField(help_text='Name to associate with this account in news feed items (e.g. Alice, Bob)', max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='paprikaaccount',
            name='username',
            field=models.CharField(help_text='Username to login to paprika', max_length=150, unique=True),
        ),
    ]
