# Generated by Django 2.0.13 on 2019-06-22 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190622_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='image_url',
        ),
        migrations.AddField(
            model_name='recipe',
            name='photo_url',
            field=models.URLField(default='', help_text='Thumbnail for recipe'),
            preserve_default=False,
        ),
    ]
