# Generated by Django 2.0.13 on 2019-06-22 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190622_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='photo_url',
            field=models.URLField(help_text='Thumbnail for recipe', max_length=1000),
        ),
    ]
