# Generated by Django 2.0.13 on 2019-06-22 18:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190622_1719'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('uid', models.CharField(db_index=True, max_length=200)),
                ('name', models.CharField(max_length=1000)),
                ('parent_uid', models.CharField(db_index=True, max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='recipe',
            name='cook_time',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='recipe',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 22, 18, 5, 28, 86634, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='difficulty',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='recipe',
            name='directions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='nutritional_info',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='on_favorites',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recipe',
            name='prep_time',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='recipe',
            name='rating',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recipe',
            name='servings',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='recipe',
            name='source',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='recipe',
            name='source_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='recipe',
            name='total_time',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='photo_hash',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='photo_url',
            field=models.URLField(blank=True, help_text='Thumbnail for recipe', max_length=1000),
        ),
    ]
