# Generated by Django 2.0.13 on 2019-06-22 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20190622_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='source_url',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
