# Generated by Django 2.0.13 on 2019-06-23 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20190622_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='paprika_account',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='core.PaprikaAccount'),
            preserve_default=False,
        ),
    ]
