# Generated by Django 2.0.13 on 2019-07-04 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20190704_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='date_ended',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Date when this version of the Recipe was superseded (unset if this is the active Recipe for this uid)', null=True),
        ),
    ]
