# Generated by Django 2.0.13 on 2019-07-05 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20190704_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='paprika_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_recipes', to='core.PaprikaAccount'),
        ),
    ]
