# Generated by Django 2.0.13 on 2019-07-07 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20190705_0256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paprikaaccount',
            name='alias',
            field=models.CharField(help_text='Your name, for displaying in news feed items (e.g. "Alice added recipe XYZ", "Bob rated recipe Y 5 stars")', max_length=150, unique=True, verbose_name='Name'),
        ),
    ]
