# Generated by Django 2.0.13 on 2019-07-28 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20190728_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='in_trash',
            field=models.BooleanField(default=False, help_text='True if recipe was deleted in Paprika app'),
        ),
    ]
