# Generated by Django 2.0.13 on 2019-08-18 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20190728_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsitem',
            name='type',
            field=models.CharField(choices=[('new_account', 'new_account'), ('recipe_added', 'recipe_added'), ('recipe_edited', 'recipe_edited'), ('recipe_rated', 'recipe_rated'), ('recipe_deleted', 'recipe_deleted')], max_length=100),
        ),
    ]
