# Generated by Django 2.1.15 on 2023-12-20 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20200907_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='paprikaaccount',
            name='jwt',
            field=models.CharField(blank=True, help_text='JWT token for v2 api', max_length=150),
        ),
    ]
