# Generated by Django 2.1.15 on 2023-12-21 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_paprikaaccount_jwt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paprikaaccount',
            name='jwt',
            field=models.CharField(blank=True, help_text='JWT token for v2 api', max_length=1000),
        ),
    ]
